apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-dporr
  labels:
    app: capstone-dporr
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-dporr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-dporr
    spec:
      containers:
      - image: dporr/capstone:30
        imagePullPolicy: Always
        name: capstone-dporr
        ports:
        - containerPort: 80
          protocol: TCP
