apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: capstone-dporr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
